### PR TITLE
First docs

### PR DESCRIPTION
**Pull request by weber-s**
Hi,

This module is pretty useful! I think it would be really nice to document it. I backmerge the master branch into this first-docs branch, and add some configuration and set the example to be easily accessible and browsable.

Thanks again for this package!
Samuël

### CODE REVIEW

**Comment by bendichter** [comment]
Interesting. I'm at a conference this week but will take a look next week. From a quick glance, I like the idea 😀

**Comment by bendichter** [comment]
I'm not familiar with this approach. Is there a reason you are PRing to a first-docs branch instead of master?

**Comment by bendichter** [comment]
oh I see I created that branch 2 years ago...

**Comment by weber-s** [comment]
Indeed, so I started on this branch. Maybe it is clever to start a new branch based on master however...

**Comment by bendichter** [comment]
I created and merged a new PR

**Pull request closed without merging**
