### PR TITLE
Add ability to fix {width,height}_ratios of GridSpec, bypassing the 1…

### LINKED ISSUE #24: Feature request of nonuniform scaling of broken regions and issue on mouse hover to plot
@developers, First thank you for this very handy tool which I just came to know yesterday.

One issue I found is on hovering mouse at different broken region on the plot, the x, y co-ordinates on line plot, does not provide the right values on the status bar of matplotlib figure.

Feature request:
 If it is possible, to have different scaling rather than 1:1 for the broken regions.

### PR DESCRIPTION
**Pull request by bendichter**
…:1 scale

fix #24

### CODE REVIEW

**Comment by bendichter** [comment]
@weber-s 

Could you make them optional args instead of hiding them in kwargs?

**Comment by weber-s** [comment]
Thanks for the PR!
I made the according change in the code, without any check in the values. I suppose GridSpec complains when width/height ratios is not a list of int by itself.

**Comment by bendichter** [comment]
Thanks! Could you please fix `height_ratios = kwargs["height_ratios"]` and add to docstring of function

**Comment by weber-s** [comment]
Woh. Reactive.

**Pull request merged**
